# Generated by Django 5.1.3 on 2024-11-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("SELLER", "Seller"), ("BUYER", "Buyer"), ("BOTH", "Both")],
                default="BUYER",
                max_length=6,
            ),
        ),
    ]
