# Generated by Django 5.1.3 on 2024-11-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
    ]
