# Generated by Django 5.1.3 on 2024-11-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
