# Generated by Django 5.1.3 on 2024-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tractorimage",
            old_name="image",
            new_name="image_1",
        ),
        migrations.AddField(
            model_name="tractorimage",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="tractor_images/"),
        ),
        migrations.AddField(
            model_name="tractorimage",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to="tractor_images/"),
        ),
    ]
